### ISSUE TITLE
I cannot open file.

### ISSUE THREAD

**Issue by ibuibu** [kezzardrix/simpleTown#1]
こんにちは。大ファンです。

AMEETの記事を読んで、ぜひとも参考にさせていただきたいのですが、ファイルが開けないのです。。TDはver2019.33840を使ってます。

**Comment by kezzardrix** [comment]
おっとエクスぺリメンタルですよね。winだと開けました。Macだったりしますか？

**Comment by ibuibu** [comment]
winですね。。。すみません、他のwinPCで、ver2019.19160だと開けました！！！お騒がせしました。。。
